language: node_js
node_js:
- node
- iojs
deploy:
  provider: heroku
  api_key:
    secure: MvOrp0R8rYCOLZ/bjL1uYRyG+W6FyvGi45AUsgv35VRmOezix1HsgBeLwT7hz8sHf04y+Ea6LvTWxXA6Jn4JFzSaIIMrHtg0eQDPIA7v06gbGAZfg52esMmDCcXeQnTBufco8X4cRLt7uMrI6lHPtbpA308s2Vobe0dn+E6JY1nxt+aR89PLVxYCnH3rgFSxVZ9NvJI+OPEOPjzMs0jcV0/x2lWMzpfm5kgL6dPV3Nt+7Ogp+y1x2QL9ggbOYtkTKnVU3jAiObeMu2jv7Jh+ELPodDaW8FO+Y3e9+r5b3u0ukfdq4G2KPl6sxMaUJjefcfCavsl6/dMCZPyA3DIScSkhyBuTZaNPoX17f7IwUo0zMCXOgFzQ7IyruFMZe2qcJPJfSjCnfE9q0m8Nr2u82dZDcO9IEmN9C/tN5Rtb+OajfYyvUd4zYDD0oUWr0XCLDGXXboZGR5VyntzgI+NB3G95noQUddluI9atDf2aLSvgbw3pJwSe+22VNQpBy1P83sAYGPoPi9UAFw66Six+VX0e2jLWb2q/K0KH5U/Xnwv3yZk4Ee6bpMZHN/nNNKtlyjJAu7RSGteA3uK5EOHjiKanNSbjWv9Wasvfsh4dodCE3EY3iWIDmAUZTcB/dG5CYoMKn2JT1kA3I/6dYLY0yu+t1l/PYDCLVRt6iLkyPvE=
